### ISSUE TITLE
Error on windows 10

### ISSUE THREAD

**Issue by NicoKiaru** [nickdelgrosso/ABBA-QuPath-RegistrationAnalysis#1]
Hi @nickdelgrosso and @enassar , 

I'm trying to run your analyzer on my win10 machine. (disclaimer: I'm not a python expert at all).

I've setup a new conda environment with python 3.8, then upgrade pip (to 21.3.1), I ran `pip install --upgrade ABBA-QuPath-RegistrationExporter`. Everything looked ok, as far as I could tell.

Then I typed `regexport`, and got this error message:

```
PySide2/__init__.py: Unable to import shiboken2 from C:\Users\chiarutt\.conda\envs\abba_analyzer\Scripts\regexport.exe, C:\Users\chiarutt\.conda\envs\abba_analyzer\python38.zip, C:\Users\chiarutt\.conda\envs\abba_analyzer\DLLs, C:\Users\chiarutt\.conda\envs\abba_analyzer\lib, C:\Users\chiarutt\.conda\envs\abba_analyzer, C:\Users\chiarutt\.conda\envs\abba_analyzer\lib\site-packages
Traceback (most recent call last):
  File "C:\Users\chiarutt\.conda\envs\abba_analyzer\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\chiarutt\.conda\envs\abba_analyzer\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\chiarutt\.conda\envs\abba_analyzer\Scripts\regexport.exe\__main__.py", line 4, in <module>
  File "C:\Users\chiarutt\.conda\envs\abba_analyzer\lib\site-packages\regexport\main.py", line 4, in <module>
    from PySide2.QtWidgets import QApplication
  File "C:\Users\chiarutt\.conda\envs\abba_analyzer\lib\site-packages\PySide2\__init__.py", line 107, in <module>
    _setupQtDirectories()
  File "C:\Users\chiarutt\.conda\envs\abba_analyzer\lib\site-packages\PySide2\__init__.py", line 58, in _setupQtDirectories
    import shiboken2
  File "C:\Users\chiarutt\.conda\envs\abba_analyzer\lib\site-packages\shiboken2\__init__.py", line 27, in <module>
    from .shiboken2 import *
ImportError: DLL load failed while importing shiboken2: The specified procedure could not be found.
```

Any idea what I could try?

Your graphs look neat, I hope I can make this work!

Thanks!

**Comment by NicoKiaru** [comment]
I managed by setting python to version 3.9
