### ISSUE TITLE
regexport not running

### ISSUE THREAD

**Issue by daniel-manrique** [nickdelgrosso/ABBA-QuPath-RegistrationAnalysis#3]
Dear Nicholas,

I really appreciate the time you have taken developing this type of tool. I would be very grateful if you can support me with something. When I try to run regexport I get the message you copy below. Could I give you some feedback on this?

Regards,

(BrainRender) C:\Users\danie>regexport
Traceback (most recent call last):
  File "C:\DataAnalysis\Anaconda\envs\BrainRender\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\DataAnalysis\Anaconda\envs\BrainRender\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\DataAnalysis\Anaconda\envs\BrainRender\Scripts\regexport.exe\__main__.py", line 4, in <module>
  File "C:\DataAnalysis\Anaconda\envs\BrainRender\lib\site-packages\regexport\main.py", line 6, in <module>
    from regexport.app import App
  File "C:\DataAnalysis\Anaconda\envs\BrainRender\lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\DataAnalysis\Anaconda\envs\BrainRender\lib\site-packages\regexport\app.py", line 10, in <module>
    from regexport.views.channel_filter import ChannelFilterView, ChannelFilterModel
  File "C:\DataAnalysis\Anaconda\envs\BrainRender\lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\DataAnalysis\Anaconda\envs\BrainRender\lib\site-packages\regexport\views\channel_filter.py", line 64
    if (num_sliders := layout.count()) > 0:
                    ^
SyntaxError: invalid syntax

**Comment by nickdelgrosso** [comment]
Hi Daniel,

This error message comes up when python version 3.7 or lower is being used; the ":=" syntax is made for python 3.8 or higher.  But to make this tool more compatible with different python versions, I've just removed the assignment expressions (commit 351f5a1d).  If you pull the latest version or update the project with `pip install --upgrade ABBA-QuPath-RegistrationExporter` it should work now.
